name: CI

on:
  pull_request:
    # CI has already been run on dev to get to main
    branches-ignore:
      - 'main'
  push:
    branches:
      - 'dev'
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  NODE_VERSION: '*'
  COVERAGE_PATH: ./coverage

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ env.REPO_NAME }}
          path: ${{ env.COVERAGE_PATH }}/**/*

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ env.COVERAGE_PATH }}
